# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-16 12:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daily', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='dtime',
        ),
        migrations.AddField(
            model_name='project',
            name='end_date',
            field=models.DateTimeField(null=True, verbose_name='EndDate'),
        ),
        migrations.AddField(
            model_name='project',
            name='start_date',
            field=models.DateTimeField(null=True, verbose_name='StartDate'),
        ),
    ]
