# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-06 09:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('daily', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('date', models.TimeField(verbose_name='Time')),
            ],
        ),
        migrations.RemoveField(
            model_name='dailyschedule',
            name='employee',
        ),
        migrations.RemoveField(
            model_name='dailyschedule',
            name='phone',
        ),
        migrations.AddField(
            model_name='employee',
            name='category',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.DeleteModel(
            name='DailySchedule',
        ),
        migrations.AddField(
            model_name='employee',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='daily.Project'),
        ),
        migrations.AddField(
            model_name='phone',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='daily.Project'),
        ),
    ]
