# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-06 09:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daily', '0002_auto_20160906_1217'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='project',
        ),
        migrations.RemoveField(
            model_name='phone',
            name='project',
        ),
        migrations.AddField(
            model_name='project',
            name='employee',
            field=models.ManyToManyField(to='daily.Employee'),
        ),
        migrations.AddField(
            model_name='project',
            name='phone',
            field=models.ManyToManyField(to='daily.Phone'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='category',
            field=models.CharField(max_length=200),
        ),
    ]
