# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-06 09:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daily', '0004_auto_20160906_1226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='category',
            field=models.CharField(max_length=200),
        ),
    ]
