# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-06 09:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daily', '0006_auto_20160906_1239'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='category',
        ),
        migrations.AddField(
            model_name='employee',
            name='category',
            field=models.ManyToManyField(to='daily.Category'),
        ),
    ]
