# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-06 10:09
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daily', '0007_auto_20160906_1244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2016, 9, 6, 13, 9, 30, 232669), verbose_name='Time'),
        ),
    ]
