# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-06 10:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daily', '0008_auto_20160906_1309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='date',
            field=models.DateTimeField(verbose_name='Time'),
        ),
    ]
