# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-06 11:18
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daily', '0009_auto_20160906_1315'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='time',
            field=models.TimeField(default=datetime.time(14, 18, 10, 500098), verbose_name='Time'),
        ),
        migrations.AlterField(
            model_name='project',
            name='date',
            field=models.DateField(default=datetime.date(2016, 9, 6), verbose_name='Date'),
        ),
    ]
