# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-06 11:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('daily', '0010_auto_20160906_1418'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='time',
            field=models.TimeField(default=django.utils.timezone.now, verbose_name='Time'),
        ),
    ]
