# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-06 11:21
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daily', '0011_auto_20160906_1419'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='time',
            field=models.TimeField(default=datetime.time(11, 21, 25, 737431), verbose_name='Time'),
        ),
    ]
