# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-06 18:44
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daily', '0012_auto_20160906_1421'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='time',
            field=models.TimeField(default=datetime.time(18, 44, 25, 541521), verbose_name='Time'),
        ),
    ]
