# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-09 02:17
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daily', '0013_auto_20160906_2144'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='project',
            name='date',
            field=models.DateField(default=datetime.date(2016, 10, 9), verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='project',
            name='time',
            field=models.TimeField(default=datetime.time(2, 17, 7, 400275), verbose_name='Time'),
        ),
        migrations.AddField(
            model_name='project',
            name='vehicle',
            field=models.ManyToManyField(to='daily.Vehicle'),
        ),
    ]
