# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-18 11:53
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daily', '0014_auto_20161009_0517'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('CMP', 'complete'), ('INCMP', 'incomplete')], default='INCMP', max_length=5),
        ),
        migrations.AlterField(
            model_name='project',
            name='date',
            field=models.DateField(default=datetime.date(2016, 10, 18), verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='project',
            name='time',
            field=models.TimeField(default=datetime.time(11, 53, 30, 404298), verbose_name='Time'),
        ),
    ]
